ALTER TABLE "Avatar" DROP COLUMN IF EXISTS "svgHappy";
ALTER TABLE "Avatar" DROP COLUMN IF EXISTS "svgSad";
ALTER TABLE "Avatar" DROP COLUMN IF EXISTS "svgSurprise";
ALTER TABLE "Avatar" DROP COLUMN IF EXISTS "svgFocused";

ALTER TABLE "Avatar" ADD COLUMN "svgGaze" TEXT;
ALTER TABLE "Avatar" ADD COLUMN "svgMouthOpen" TEXT;
